Repository Hares-2088/TravelTrove, pull requests merged in 2024-12, with the labels that each got.

#3 feat(TT-59): manage countries
  .gitignore
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/country/CountryService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/country/CountryServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/country/Country.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/country/CountryRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/country/CountryController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/country/CountryRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/country/CountryResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/DataLoaderService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/DatabaseLoader.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/EntityModelUtil.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/TourServiceUnitTest.java
  fe-traveltrove/public/assets/icons/globe.png
  fe-traveltrove/src/features/countries/api/countries.api.ts
  fe-traveltrove/src/features/countries/models/country.model.ts
  fe-traveltrove/src/features/staff/components/CountriesTab.css
  fe-traveltrove/src/features/staff/components/CountriesTab.tsx
  fe-traveltrove/src/features/staff/components/Dashboard.tsx
  fe-traveltrove/src/index.tsx
  fe-traveltrove/src/layouts/Footer.css
  fe-traveltrove/src/layouts/Footer.tsx
  fe-traveltrove/src/layouts/NavBar.css
  fe-traveltrove/src/layouts/NavBar.tsx
  fe-traveltrove/src/pages/staff/DashboardPage.tsx
  fe-traveltrove/src/router.tsx
  fe-traveltrove/src/shared/models/app.routes.ts
Labels: enhancement, Package Management

#4 bug(TT-62): fix update country
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/country/CountryService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/country/CountryServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/country/CountryController.java
Labels: bug

#14 feat(TT-64): manage tour events
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourEventService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourEventServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourEventsService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourEventsServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tour/TourServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/city/City.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/country/Country.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/events/Event.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/Tour.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourEvent.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourEventRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourEventsRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourEventController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourEventRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourEventResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourEventsController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourEventsRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tour/TourEventsResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/DatabaseLoader.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/EntityModelUtil.java
Labels: enhancement, Package Management

#24 finished the diagrams for sprint 1 and 2
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/city/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/city/Design-Level_Sequence_Diagram_Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/country/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/country/Design-Level_Sequence_Diagram_Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/event/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/event/Design-Level_Sequence_Diagram_Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/tour/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/tour/Design-Level_Sequence_Diagram_Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/tour_event/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint1/tour_event/Design-Level_Sequence_Diagram_Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Airport/Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Airport/Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Airport/Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Airport/FromTourPackage/Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Airport/FromTourPackage/Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Hotel/Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Hotel/Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Hotel/Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Hotel/FromTourPackage/Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Hotel/FromTourPackage/Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Tour_Packages/Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Tour_Packages/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Tour_Packages/Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/Tour_Packages/Not_Logged_In_Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/booking/Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/booking/Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/booking/Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/user/Design-Level_Sequence_Diagram_Admin.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/user/Design-Level_Sequence_Diagram_Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/user/Design-Level_Sequence_Diagram_Employee.puml
  diagrams/Design_Level_Sequence_Diagrams/Sprint2/user/Design-Level_Sequence_Diagram_Not_Registered_Customer.puml
  diagrams/Design_Level_Sequence_Diagrams/test.puml
Labels: documentation

#28 feat_TT-64_Manage_Tour_Events
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourEvent.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tour/TourEventServiceUnitTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/tour/TourEventRepositoryIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/tour/TourRepositoryIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigTourEventService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/tour/TourEventControllerIntegrationTest.java
  fe-traveltrove/.github/workflows/playwright.yml
  fe-traveltrove/playwright.config.ts
  fe-traveltrove/src/features/staff/components/TourEventsTab.tsx
  fe-traveltrove/tests/tourevents.spec.ts
Labels: tests

#29 Use cases sprint 1 and 2
  diagrams/DesignClassDiagrams/Sprint 1/CityDesignClassDiagram.puml
  diagrams/DesignClassDiagrams/Sprint 1/CountryDesignClassDiagram.puml
  diagrams/DesignClassDiagrams/Sprint 1/TourEventDesignClassDiagram.puml
  diagrams/System_Requirements/Sprint1/City
  diagrams/System_Requirements/Sprint1/Country
  diagrams/System_Requirements/Sprint1/Event
  diagrams/System_Requirements/Sprint1/Tour
  diagrams/System_Requirements/Sprint1/TourEvent
  diagrams/System_Requirements/Sprint2/Booking
  diagrams/System_Requirements/Sprint2/Hotels
  diagrams/System_Requirements/Sprint2/Tour Packages
  diagrams/System_Requirements/Sprint2/Users
  diagrams/System_Requirements/Sprint2/airports
  diagrams/use cases/Sprint1/city/Admin.puml
  diagrams/use cases/Sprint1/city/Employee.puml
  diagrams/use cases/Sprint1/country/Admin.puml
  diagrams/use cases/Sprint1/country/Employee.puml
  diagrams/use cases/Sprint1/event/Admin.puml
  diagrams/use cases/Sprint1/event/Employee.puml
  diagrams/use cases/Sprint1/tour/Admin.puml
  diagrams/use cases/Sprint1/tour/Employee.puml
  diagrams/use cases/Sprint1/tour_event/Admin.puml
  diagrams/use cases/Sprint1/tour_event/Employee.puml
  diagrams/use cases/Sprint2/Hotel/Admin.puml
  diagrams/use cases/Sprint2/Hotel/Customer.puml
  diagrams/use cases/Sprint2/Hotel/Employee.puml
  diagrams/use cases/Sprint2/Hotel/Not_Logged_In_Customer.puml
  diagrams/use cases/Sprint2/User/Admin.puml
  diagrams/use cases/Sprint2/User/Customer.puml
  diagrams/use cases/Sprint2/User/Employee.puml
  diagrams/use cases/Sprint2/User/Not_Logged_In_Customer.puml
  diagrams/use cases/Sprint2/airport/Admin.puml
  diagrams/use cases/Sprint2/airport/Customer.puml
  diagrams/use cases/Sprint2/airport/Employee.puml
  diagrams/use cases/Sprint2/booking/Admin.puml
  diagrams/use cases/Sprint2/booking/Employee.puml
  diagrams/use cases/Sprint2/booking/customer.puml
  diagrams/use cases/Sprint2/tour_packages/Admin.puml
  diagrams/use cases/Sprint2/tour_packages/Customer.puml
  diagrams/use cases/Sprint2/tour_packages/employee.puml
Labels: documentation

#47 Feat/(TT-70) manage packages
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tourpackage/PackageService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/user/UserServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/Package.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/PackageRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/DatabaseLoader.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/entitymodels/PackageEntityModelUtil.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/entitymodels/UserEntityToModel.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceUnitTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/PackageRepositoryIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigPackageService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageControllerIntegrationTest.java
  fe-traveltrove/public/locales/en/translation.json
  fe-traveltrove/src/features/packages/api/packages.api.ts
  fe-traveltrove/src/features/packages/models/package.model.ts
  fe-traveltrove/src/features/staff/components/TourPackagesTab.tsx
  fe-traveltrove/src/features/staff/components/ToursTab.tsx
  fe-traveltrove/tests/packages.spec.ts
Labels: Package Management, Staff Management, tests
