Repository Hares-2088/TravelTrove, pull requests merged in 2025-01, with the labels that each got.

#60 doc(TT): Diagrams changes for package
  diagrams/C4_l3/C4_l3_database.puml
  diagrams/DDD.puml
  diagrams/Design_Level_Class_Diagrams/Design_Class_Level_Diagrams/SPRINT2(I_THINK)/Tour_Package.puml
  diagrams/Design_Level_Class_Diagrams/Design_Class_Level_Diagrams/SPRINT2/Airport.puml
  diagrams/Design_Level_Class_Diagrams/Design_Class_Level_Diagrams/SPRINT2/Hotel.puml
  diagrams/Design_Level_Class_Diagrams/Design_Class_Level_Diagrams/SPRINT2/Package.puml
  diagrams/Design_Level_Class_Diagrams/Design_Class_Level_Diagrams/SPRINT2/booking.puml
  diagrams/Design_Level_Class_Diagrams/Design_Class_Level_Diagrams/SPRINT2/user.puml
  diagrams/Design_Level_Class_Diagrams/ViewTourPackages.puml
Labels: documentation

#62 bug(TT-86): fix failing build on frontend
  fe-traveltrove/src/features/staff/components/Tabs/TourEventsTab.tsx
Labels: bug

#64 bug(TT:87) fix security config
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/config/security/SecurityConfig.java
Labels: bug

#70 feat(TT-37): account creation notification
  be-traveltrove/build.gradle
  be-traveltrove/gradlew
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/notification/NotificationService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/notification/NotificationServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/traveler/TravelerService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/traveler/TravelerServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/user/UserServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/airport/AirportRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/booking/BookingRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/city/CityRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/events/EventRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/hotel/HotelRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/notification/Notification.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/notification/NotificationRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/review/ReviewRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourEventRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tour/TourRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/PackageRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/traveler/TravelerRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/user/UserRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/notification/NotificationController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/notification/NotificationRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/notification/NotificationResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/traveler/TravelerController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/traveler/TravelerWithIdRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/user/UserController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/DatabaseLoader.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/entitymodelyutils/TravelerEntityModelUtil.java
  be-traveltrove/src/main/resources/application.yml
  be-traveltrove/src/main/resources/email-templates/booking-confirmation-email.html
  be-traveltrove/src/main/resources/email-templates/custom-email.html
  be-traveltrove/src/main/resources/email-templates/limited-spots-email.html
  be-traveltrove/src/main/resources/email-templates/post-trip-review-email.html
  be-traveltrove/src/main/resources/email-templates/tour-update-email.html
  be-traveltrove/src/main/resources/email-templates/welcome-email.html
  fe-traveltrove/src/features/notifications/api/notifications.api.ts
  fe-traveltrove/src/features/notifications/models/notification.model.ts
  fe-traveltrove/src/features/staff/components/Dashboard.tsx
  fe-traveltrove/src/features/staff/components/Tabs/NotificationsTab.tsx
  fe-traveltrove/src/features/staff/components/Tabs/TravelersTab.tsx
  fe-traveltrove/src/features/users/components/ProfileCreateForm.css
  fe-traveltrove/src/features/users/components/ProfileCreateForm.tsx
  fe-traveltrove/src/pages/user/ProfileCreatePage.tsx
  fe-traveltrove/src/pages/user/ProfilePage.tsx
Labels: enhancement, Notification

#72 feat(TT-5): Access Control
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/user/UserControllerIntegrationTest.java
  fe-traveltrove/src/App.tsx
  fe-traveltrove/src/context/UserContext.tsx
  fe-traveltrove/src/features/users/api/users.api.ts
  fe-traveltrove/src/index.tsx
  fe-traveltrove/src/router.tsx
  fe-traveltrove/src/shared/components/ProtectedComponent.tsx
  fe-traveltrove/src/shared/components/ProtectedRoute.tsx
Labels: Authentication

#74 bug(TT-89): fix protected routes
  fe-traveltrove/src/App.tsx
  fe-traveltrove/src/router.tsx
  fe-traveltrove/src/shared/components/ProtectedRoute.tsx
Labels: bug

#69 bug(TT-88): fixed the bug in the controller tests with the auth
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/BeTraveltroveApplicationTests.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tour/TourEventServiceUnitTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceUnitTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/airport/AirportRepositoryIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/booking/BookingRepositoryIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/city/CityRepositoryIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/dataaccess/city/CityRepositoryUnitTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/airport/AirportControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/booking/BookingControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/city/CityControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/country/CountryControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/event/EventControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/hotel/HotelControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigAirportService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigBookingService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigCityService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigCountryService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigEventService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigHotelService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigPackageService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigTourEventService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigTourService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigTravelerService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/mockserverconfigs/MockServerConfigUserService.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/tour/TourControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/tour/TourEventControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/traveler/TravelerControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/user/UserControllerIntegrationTest.java
Labels: bug

#75 bug(TT-89): fix protected routes
  fe-traveltrove/src/router.tsx
Labels: bug

#81 bug(TT-94): User Management Page Returns 404 Not Found
  fe-traveltrove/src/layouts/NavBar.tsx
  fe-traveltrove/src/router.tsx
  fe-traveltrove/src/shared/models/app.routes.ts
Labels: bug

#82 feat(TT-41): subscribe to a tour package
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tourpackage/SubscriptionService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tourpackage/SubscriptionServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/Subscription.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/SubscriptionRepository.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/SubscriptionController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/SubscriptionRequestModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/SubscriptionResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/entitymodelyutils/SubscriptionEntityModelUtil.java
  diagrams/SSD/CUST2.puml
  fe-traveltrove/src/features/packages/api/subscriptions.api.ts
  fe-traveltrove/src/features/packages/components/PackageDetails.css
  fe-traveltrove/src/features/packages/components/PackageDetails.tsx
  fe-traveltrove/src/features/packages/models/subscription.model.ts
Labels: enhancement

#83 Feat/tt 73 package status implementation
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/booking/BookingService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/booking/BookingServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tourpackage/PackageService.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceImpl.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/booking/BookingStatus.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/Package.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/dataaccess/tourpackage/PackageStatus.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageController.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageRequestStatus.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageResponseModel.java
  be-traveltrove/src/main/java/com/traveltrove/betraveltrove/utils/DatabaseLoader.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/business/tourpackage/PackageServiceUnitTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/booking/BookingControllerIntegrationTest.java
  be-traveltrove/src/test/java/com/traveltrove/betraveltrove/presentation/tourpackage/PackageControllerIntegrationTest.java
  diagrams/Sprint4/Packages/StateTransitionPackages.puml
  fe-traveltrove/src/features/packages/api/packages.api.ts
  fe-traveltrove/src/features/packages/components/PackageDetails.tsx
  fe-traveltrove/src/features/packages/components/PackageList.css
  fe-traveltrove/src/features/packages/components/PackageList.tsx
  fe-traveltrove/src/features/packages/models/package.model.ts
  fe-traveltrove/src/features/staff/components/Tabs/TourPackagesTab.tsx
  fe-traveltrove/src/features/tours/components/TourDetails.tsx
  fe-traveltrove/src/features/tours/components/ToursList.tsx
  fe-traveltrove/tests/packages.spec.ts
Labels: enhancement, Booking, Staff Management
